// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260101140124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Shared.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("Shared.Models.ChoreAdmin", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChoreId", "UserId");

                    b.ToTable("ChoreAdmins");
                });

            modelBuilder.Entity("Shared.Models.ChoreDescription", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChoreId");

                    b.ToTable("ChoreDescriptions");
                });

            modelBuilder.Entity("Shared.Models.ChoreLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreLogs");
                });

            modelBuilder.Entity("Shared.Models.ChoreMember", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RotationOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChoreId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreMembers");
                });

            modelBuilder.Entity("Shared.Models.ChoreQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId", "AssignedMemberId");

                    b.ToTable("ChoreQueue");
                });

            modelBuilder.Entity("Shared.Models.ChoreSchedule", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ChoreId");

                    b.ToTable("ChoreSchedules");
                });

            modelBuilder.Entity("Shared.Models.ChoreState", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextMemberIdx")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChoreId");

                    b.ToTable("ChoreStates");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.Chore", b =>
                {
                    b.HasOne("Shared.Models.User", "Owner")
                        .WithMany("OwnedChores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Shared.Models.ChoreAdmin", b =>
                {
                    b.HasOne("Shared.Models.ChoreMember", "Member")
                        .WithOne("AdminRole")
                        .HasForeignKey("Shared.Models.ChoreAdmin", "ChoreId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Shared.Models.ChoreDescription", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithOne("Description")
                        .HasForeignKey("Shared.Models.ChoreDescription", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("Shared.Models.ChoreLog", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithMany("Logs")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.ChoreMember", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithMany("Members")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.ChoreQueue", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithMany("QueueItems")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.ChoreMember", "AssignedMember")
                        .WithMany()
                        .HasForeignKey("ChoreId", "AssignedMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("Shared.Models.ChoreSchedule", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithOne("Schedule")
                        .HasForeignKey("Shared.Models.ChoreSchedule", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("Shared.Models.ChoreState", b =>
                {
                    b.HasOne("Shared.Models.Chore", "Chore")
                        .WithOne("State")
                        .HasForeignKey("Shared.Models.ChoreState", "ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("Shared.Models.Chore", b =>
                {
                    b.Navigation("Description");

                    b.Navigation("Logs");

                    b.Navigation("Members");

                    b.Navigation("QueueItems");

                    b.Navigation("Schedule");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Shared.Models.ChoreMember", b =>
                {
                    b.Navigation("AdminRole");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Memberships");

                    b.Navigation("OwnedChores");
                });
#pragma warning restore 612, 618
        }
    }
}
